<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'workshops' => 'Workshops',
		'workshops.registration' => 'Registration',
		'workshops.relations' => 'Relations',
		'workshops.type.I.0' => 'Workshops',
		'workshops.type.I.1' => 'Link internal Page',
		'workshops.type.I.2' => 'Link external URL',
		'workshops.datetime' => 'Date/Time of item creation:',
		'workshops.archivedate' => 'Archive date:',
		'workshops.datetime_begin' => 'Begin of workshop:',
		'workshops.datetime_end' => 'End of workshop:',
		'workshops.showTime' => 'Show time of begin and end',
		'workshops.showTime_always' => 'always',
		'workshops.showTime_onlySingle' => 'only in single view',
		'workshops.showTime_never' => 'never',
		'workshops.datetime_alternative' => 'Alternative begin/end',
		'workshops.city' => 'City (will be shown in overview):',
		'workshops.address' => 'Complete Address of workshop:',
		'workshops.contact_person' => 'Contact person:',
		'workshops.contact_email' => 'Contact e-mail:',
		'workshops.contact_phone' => 'Contact phone:',
		'workshops.show_details' => 'Show details:',
		'workshops.show_regform' => 'Show registration form:',
		'workshops.imagelink' => 'Image link:',
		'workshops.regformfile' => 'Registration form:',
		'workshops.status' => 'Status:',
		'workshops.status_hide' => 'k.A.',
		'workshops.status_green' => 'noch nicht ausgebucht',
		'workshops.status_yellow' => 'fast ausgebucht',
		'workshops.status_red' => 'ausgebucht',
		'workshops.myMessageText' => 'My Message:',
		'workshops.fee' => 'Fee:',
		'workshops.feeText' => 'Fee text:',
		'workshops.reduced' => 'Reduced fee:',
		'workshops.reducedText' => 'Reduced fee text:',
		'workshops.singlebed' => 'Single bed:',
		'workshops.singlebedText' => 'Single bed text:',
		'workshops.vegetarian' => 'Vegetarian food:',
		'workshops.vegetarianText' => 'Vegetarian food text:',
		'workshops.registrationFinalText' => 'Final registration text:',
		'workshops.regformData' => 'Registration form (expert modus):',
		'workshops.related' => 'Related workshops:',
		'workshops.regMailRecipient' => 'Recipient of registration mail/Workshop administration:',
		'workshops.confMailSubject' => 'Subject of confirmation mail:',
		'workshops.confMailBody' => 'Body of confirmation mail:',
		'workshops.confMailStdSignature' => 'Use standard signature?',
		'workshops_cat' => 'Workshops category',
		'workshops_cat.image' => 'Category image',
		'workshops_cat.title_lang_ol' => 'title language overlays',
		'workshops_cat.shortcut' => 'Workshops category shortcut',
		'workshops_cat.shortcut_target' => 'Target for workshops category shortcut',
		'workshops.pi_flexform.sheet_general' => 'General Settings',
		'workshops.pi_flexform.sheet_template' => 'Template',
		'workshops.pi_flexform.sheet_category' => 'Category Settings',
		'workshops.pi_flexform.sheet_registration' => 'Registration Settings',
		'workshops.pi_flexform.sheet_misc' => 'Other Settings',
		'workshops.pi_flexform.what_to_display' => 'What to display:',
		'workshops.pi_flexform.listOrderby' => '"Order by" this field (LIST & LATEST):',
		'workshops.pi_flexform.ascDesc' => 'Ascending or Descending (LIST & LATEST):',
		'workshops.pi_flexform.ascDesc_asc' => 'Ascending',
		'workshops.pi_flexform.ascDesc_desc' => 'Descending',
		'workshops.pi_flexform.select_deselect_categories' => 'Category mode:',
		'workshops.pi_flexform.category_selection_notCategorized' => '[not categorized]',
		'workshops.pi_flexform.category_selection' => 'Category selection',
		'workshops.pi_flexform.category_selection_showAll' => 'Show all (don\'t care about selection below)',
		'workshops.pi_flexform.category_selection_showSelected' => 'Show items with selected categories',
		'workshops.pi_flexform.category_selection_DontShowSelected' => 'Do NOT show items with selected categories',
		'workshops.pi_flexform.archive' => 'Archive setting (for LIST)',
		'workshops.pi_flexform.template_file' => 'Template file',
		'workshops.pi_flexform.catImageMode' => 'Category Image Link Mode:',
		'workshops.pi_flexform.catTextMode' => 'Category Text Link Mode:',
		'workshops.pi_flexform.recursive' => 'Recursive level selection:',
		'workshops.pi_flexform.catImageMaxWidth' => 'Max width of category image:',
		'workshops.pi_flexform.catImageMaxHeight' => 'Max height of category image:',
		'workshops.pi_flexform.maxCatImages' => 'Max number of category images:',
		'workshops.pi_flexform.maxTextLength' => 'Max length of category text:',
		'workshops.pi_flexform.maxCatTexts' => 'Max number of categorys texts:',
		'workshops.pi_flexform.PIDitemDisplay' => 'PageId for single item display:',
		'workshops.pi_flexform.backPid' => 'PageId to return to:',
		'workshops.pi_flexform.archive_nonarc' => 'SHOW NON-ARCHIVED',
		'workshops.pi_flexform.archive_arc' => 'SHOW ARCHIVED',
		'workshops.pi_flexform.archive_dontcare' => 'Don\'t Care',
		'workshops.pi_flexform.catLinkMode_TS' => 'Defined by TypoScript',
		'workshops.pi_flexform.catLinkMode_dontshow' => 'Don\'t display at all',
		'workshops.pi_flexform.catLinkMode_shownolink' => 'Display, but no links',
		'workshops.pi_flexform.catLinkMode_catshortcut' => 'Acts as link to category shortcuts',
		'workshops.pi_flexform.catLinkMode_catsel' => 'Acts as a category selector',
		'workshops.pi_flexform.firstImageIsPreview' => 'Don\'t display first image in single view (firstImageIsPreview)',
		'workshops.pi_flexform.limit' => 'Limit: max items in LIST (and LATEST, if no \'latestLimit\' is set)',
		'workshops.pi_flexform.listStartId' => 'List StartId: Force LIST or LATEST to start from this item',
		'workshops.pi_flexform.noPageBrowser' => 'Don\'t display Pagebrowser',
		'workshops.pi_flexform.imageMaxWidth' => 'Max width for images in workshops records',
		'workshops.pi_flexform.imageMaxHeight' => 'Max height for images in workshops records',
		'workshops.pi_flexform.alternatingLayouts' => 'Number of alternating template-layouts',
		'workshops.pi_flexform.croppingLength' => 'stdWrap.crop for the subheader (short)',
		'workshops.pi_flexform.myMessageText' => 'Alt.-Label of "My message":',
		'workshops.pi_flexform.feeText' => 'Text to display with fee (Use \'|\' to mark position of fee):',
		'workshops.pi_flexform.reducedText' => 'Text to display with reduced fee (Use \'|\' to mark position of reduced fee):',
		'workshops.pi_flexform.singlebedText' => 'Text to display for singlebed extra price (Use \'|\' to mark position of extra fee):',
		'workshops.pi_flexform.vegetarianText' => 'Text to display for vegetarian food (Use \'|\' to mark position of extra fee):',
		'workshops.pi_flexform.registrationFinalText' => 'Final registration text:',
		'workshops.pi_flexform.regMailSubject' => 'Subject of registration mail (Use \'|\' to mark position of workshop title):',
		'workshops.pi_flexform.regMailRecipient' => 'Recipient of registration mail (= workshop administration):',
		'workshops.pi_flexform.PIDconfDisplay' => 'PageID for registration confirmation display:',
		'workshops.pi_flexform.confMailSubject' => 'Subject of confirmation mail (Use \'|\' to mark position of workshop title):',
		'workshops.pi_flexform.confMailThankyou' => 'Thankyou string of confirmation mail (Use \'|\' to mark position of workshop title):',
		'workshops.pi_flexform.confMailContact' => 'Contact information text of confirmation mail (Use \'|\' to mark position of contact information):', 
		'workshops.pi_flexform.confMailSignature' => 'Signature of confirmation mail:'
	),
	'dk' => Array (
	),
	'de' => Array (
		'workshops' => 'Seminare',
		'workshops.registration' => 'Anmeldung',
		'workshops.relations' => 'Verweise',
		'workshops.type.I.0' => 'Seminare',
		'workshops.type.I.1' => 'Link zu interner Seite',
		'workshops.type.I.2' => 'Link zu externer URL',
		'workshops.datetime' => 'Abfassungsdatum/-zeit:',
		'workshops.archivedate' => 'Archivdatum:',
		'workshops.datetime_begin' => 'Veranstaltungsbeginn:',
		'workshops.datetime_end' => 'Veranstaltungsende:',
		'workshops.showTime' => 'Uhrzeiten anzeigen',
		'workshops.showTime_always' => 'immer',
		'workshops.showTime_onlySingle' => 'nur in der Einzelansicht',
		'workshops.showTime_never' => 'nie',
		'workshops.datetime_alternative' => 'Alternativer Zeittext',
		'workshops.city' => 'Ort (wird in der Übersicht angezeigt):',
		'workshops.address' => 'Vollständige Adresse des Veranstaltungsortes:',
		'workshops.contact_person' => 'Ansprechpartner:',
		'workshops.contact_email' => 'Ansprechpartner Email:',
		'workshops.contact_phone' => 'Ansprechpartner Telefon:',
		'workshops.show_details' => 'Einzelansicht anzeigen:',
		'workshops.show_regform' => 'Anmeldeformular anzeigen:',
		'workshops.imagelink' => 'Bildverweis:',
		'workshops.regformfile' => 'Anmeldeformular:',
		'workshops.status' => 'Buchungsstatus:',
		'workshops.status_green' => 'noch Plätze frei',
		'workshops.status_yellow' => 'fast ausgebucht',
		'workshops.status_red' => 'ausgebucht',
		'workshops.myMessageText' => 'Label für Anmelder-Nachricht:',
		'workshops.fee' => 'Teilnahmebeitrag:',
		'workshops.feeText' => 'Text zum Teilnahmebeitrag:',
		'workshops.reduced' => 'Ermäßigter Teilnahmebeitrag:',
		'workshops.reducedText' => 'Text zum ermäßigten Teilnahmebeitrag:',
		'workshops.singlebed' => 'Einzelzimmerzuschlag:',
		'workshops.singlebedText' => 'Text zum Einzelzimmerzuschlag:',
		'workshops.vegetarian' => 'Vegetarische Ernährung:',
		'workshops.vegetarianText' => 'Text bei vegetarischer Ernährung:',
		'workshops.registrationFinalText' => 'Text am Ende der Anmeldung:',
		'workshops.regformData' => 'Anmeldeformular (Expertenmodus):',
		'workshops.related' => 'In Verbindung stehende Seminare:',
		'workshops.regMailRecipient' => 'Anmeldemail-Empfänger/Seminarverwaltung:',
		'workshops.confMailSubject' => 'Betreff der Bestätigungsmail:',
		'workshops.confMailBody' => 'Text der Bestätigungsmail:',
		'workshops.confMailStdSignature' => 'Standard Signature benutzen?',
		'workshops_cat' => 'Seminar Kategorie',
		'workshops_cat.image' => 'Kategoriebild',
		'workshops_cat.title_lang_ol' => 'Sprachlayer für Titel',
		'workshops_cat.shortcut' => 'Seminar Kategorie Kürzel',
		'workshops_cat.shortcut_target' => 'Ziel für Seminar Kategorie Kürzel',
		'workshops.pi_flexform.sheet_general' => 'Allgemeine Einstellungen',
		'workshops.pi_flexform.sheet_template' => 'Template Einstellungen',
		'workshops.pi_flexform.sheet_category' => 'Kategorie Einstellungen',
		'workshops.pi_flexform.sheet_registration' => 'Anmeldungseinstellungen',
		'workshops.pi_flexform.sheet_misc' => 'Sonstige Einstellungen',
		'workshops.pi_flexform.what_to_display' => 'Ansicht:',
		'workshops.pi_flexform.listOrderby' => 'Feld für "Sortieren" (LIST & LATEST):',
		'workshops.pi_flexform.ascDesc' => 'aufsteigend oder absteigend (LIST & LATEST):',
		'workshops.pi_flexform.ascDesc_asc' => 'aufsteigend',
		'workshops.pi_flexform.ascDesc_desc' => 'absteigend',
		'workshops.pi_flexform.select_deselect_categories' => 'Kategoriemodus:',
		'workshops.pi_flexform.category_selection' => 'Kategorieauswahl:',
		'workshops.pi_flexform.archive' => 'Archiveinstellungen (für LIST Ansicht):',
		'workshops.pi_flexform.template_file' => 'Template Datei',
		'workshops.pi_flexform.catImageMode' => 'Kategoriebild Link Mode:',
		'workshops.pi_flexform.catTextMode' => 'Kategorietext Link Mode:',
		'workshops.pi_flexform.recursive' => 'Rekursiv:',
		'workshops.pi_flexform.catImageMaxWidth' => 'Maximale Breite für Kategoriebild:',
		'workshops.pi_flexform.catImageMaxHeight' => 'Maximale Höhe für Kategoriebild:',
		'workshops.pi_flexform.maxCatImages' => 'Maximale Anzahl für Kategoriebilder:',
		'workshops.pi_flexform.maxTextLength' => 'Maximale Länge für Kategorietext:',
		'workshops.pi_flexform.maxCatTexts' => 'Maximale Anzahl für Kategorietexte:',
		'workshops.pi_flexform.PIDitemDisplay' => 'Seite für die SINGLE-Anzeige (Seminardetails):',
		'workshops.pi_flexform.backPid' => 'Seite für \'Zurück\':',
		'workshops.pi_flexform.archive_nonarc' => 'Nur nicht-archivierte',
		'workshops.pi_flexform.archive_arc' => 'Nur archivierte',
		'workshops.pi_flexform.archive_dontcare' => 'Egal',
		'workshops.pi_flexform.catLinkMode_TS' => 'Definiert durch TypoScript',
		'workshops.pi_flexform.catLinkMode_dontshow' => 'Nicht anzeigen',
		'workshops.pi_flexform.catLinkMode_shownolink' => 'Anzeigen aber ohne Link',
		'workshops.pi_flexform.catLinkMode_catshortcut' => 'Anzeigen und Link zum Kategorie-Shortcut',
		'workshops.pi_flexform.catLinkMode_catsel' => 'Anzeigen und Link als Kategorieselektor',
		'workshops.pi_flexform.firstImageIsPreview' => 'Erstes Bild in SINGLE-Anzeige (Seminardetails) NICHT anzeigen (firstImageIsPreview)',
		'workshops.pi_flexform.limit' => 'Max. Anzahl Datensätze in LIST-Anzeige (und in LATEST-Anzeige, falls \'latestLimit\' nicht gesetzt)',
		'workshops.pi_flexform.listStartId' => 'LIST StartId: LIST oder LATEST müssen mit diesem Datensatz starten',
		'workshops.pi_flexform.noPageBrowser' => 'Pagebrowser nicht anzeigen',
		'workshops.pi_flexform.imageMaxWidth' => 'Max. Breite der Bilder in der Seminar-Datenbank',
		'workshops.pi_flexform.imageMaxHeight' => 'Max Höhe der Bilder in der Seminar-Datenbank',
		'workshops.pi_flexform.alternatingLayouts' => 'Anzahl der Wechsel-Vorlagen',
		'workshops.pi_flexform.croppingLength' => 'Max. Länge für die Kurzform der Unter-Kopfzeile',
		'workshops.pi_flexform.myMessageText' => 'Alternativer Bezeichner für "Meine Nachricht":',
		'workshops.pi_flexform.feeText' => 'Text beim Teilnahmebeitrag (mit \'|\' Position des Beitrags markieren):',
		'workshops.pi_flexform.reducedText' => 'Text beim ermäßigten Teilnahmebeitrag (mit \'|\' Position des Beitrags markieren):',
		'workshops.pi_flexform.singlebedText' => 'Text für Einzelzimmer (mit \'|\' Position des Beitrags markieren):',
		'workshops.pi_flexform.vegetarianText' => 'Text für vegetarische Verpflegung (mit \'|\' Position des Beitrags markieren):',
		'workshops.pi_flexform.registrationFinalText' => 'Text am Ende der Anmeldung:',
		'workshops.pi_flexform.regMailSubject' => 'Betreff für die Anmeldemail (mit \'|\' Position des Seminartitels markieren):',
		'workshops.pi_flexform.regMailRecipient' => 'Anmeldemail-Empfänger (= Seminarverwaltung):',
		'workshops.pi_flexform.PIDconfDisplay' => 'Seite für die Registrierungsbestätigungsanzeige:',
		'workshops.pi_flexform.confMailSubject' => 'Betreff für die Bestätigungsmail (mit \'|\' Position des Seminartitels markieren):',
		'workshops.pi_flexform.confMailThankyou' => 'Danke-Text für die Bestätigungsmail (mit \'|\' Position des Seminartitels markieren):',
		'workshops.pi_flexform.confMailContact' => 'Kontaktdaten-Text für die Bestätigungsmail (mit \'|\' Position der Kontaktdaten markieren):',
		'workshops.pi_flexform.confMailSignature' => 'Signatur der Bestätigungsmail:'
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
);
?>